trigger:
  - main  # Runs on changes to the main branch
resources:
  repositories:
  - repository: self
    type: git
    name: Devops Project
    ref: main
    public: true  # 👈 Explicitly declare as public

variables:
  DOCKERHUB_REPO: 'nizam799/docker-repo1'  # Format: <username>/<repo>
  VM_IP: '20.169.224.172'            # Replace with your VM's IP
  VM_USERNAME: 'snp'      # SSH username
  IPADD: '*'
  CONTNAME: 'crono'

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self  # Pulls code from Azure Repos

          # Log in to Docker Hub using a service connection
          - task: Docker@2
            displayName: Login to Docker Hub
            inputs:
              command: login
              containerRegistry: 'Azure-Dev-Py-Doc'  # Name of your Docker Hub service connection

          # Build and push to Docker Hub
          - task: Docker@2
            displayName: Build and Push to Docker Hub
            inputs:
              command: buildAndPush
              repository: $(DOCKERHUB_REPO)
              dockerfile: '**/Dockerfile'
              tags: 'latest'

  - stage: DeployToVM
    displayName: Deploy to Ubuntu VM
    dependsOn: BuildAndPush
    jobs:
      - job: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              ssh $(VM_USERNAME)@$(VM_IP) "
                docker pull $(DOCKERHUB_REPO):latest
                docker stop $(CONTNAME) || true
                docker rm $(CONTNAME) || true
                docker run -d -p 8000:8000 \
                 --name $(CONTNAME) \
                 -e IPADD='$(IPADD)' \
                 $(DOCKERHUB_REPO):latest
              "
            displayName: 'SSH and Run Container'