name: Build and Deploy to VM

on:
  push:
    branches: [ main ]

env:
  GHCR_REPO: 'ghcr.io/nizam799/django'  # GitHub Container Registry format
  VM_IP: '20.169.224.172'
  VM_USERNAME: 'snp'
  IPADD: '*'
  CONTNAME: 'cronto'
  VERSION: 'testV2'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Needed to push to GHCR
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.GHCR_REPO }}:${{ env.VERSION }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}

  deploy-to-vm:
    name: Deploy to Ubuntu VM
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.VM_IP }}
          username: ${{ env.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin || echo "Login failed"
            docker pull ${{ env.GHCR_REPO }}:${{ env.VERSION }} || echo "Pull Failed"
            docker stop ${{ env.CONTNAME }} 2>/dev/null || echo "No Container to stop"
            docker rm ${{ env.CONTNAME }} 2>/dev/null || echo "No container to remove"
            docker run -d --restart unless-stopped -p 8000:8000 --name ${{ env.CONTNAME }} -e IPADD=${{ env.IPADD }} ${{ env.GHCR_REPO }}:${{ env.VERSION }}